jQuery(document).ready(function(){
	jQuery('.desktop').outerHeight(jQuery(window).height());
	jQuery('.windowManager').outerHeight(jQuery(window).height());
	jQuery('.windowManager').outerWidth(jQuery(window).width()-75);
	jQuery(window).resize(function(){
		jQuery('.desktop').outerHeight(jQuery(window).height());
		jQuery('.windowManager').outerHeight(jQuery(window).height());
		jQuery('.windowManager').outerWidth(jQuery(window).width()-75);
	});
});