<?php Ressource::getCurrentLanguage()->init('module/ModelListingDescriptor'); ?>
<?php Ressource::getCurrentLanguage()->init('module/ModelListingDescriptor.'.$this->getModel()); ?>
<?php  Ressource::getCurrentPage()->addJS(Ressource::getCurrentTemplate()->getFile(new File('js/module','ModelListing.js',false)),0); ?>
<script> 
AjaxHTMLFetcher.setFetcher('new_<?php echo $this->model; ?>',new URL(Ressource.getConfiguration().getValue('AliasName')+'model_editor/<?php echo $this->getConfParam('modelEditor'); ?>/','model=<?php echo $this->model; ?>&source=create'),function(htmlContent){

	var window = new Window();
	window.setConfiguration(<?php echo json_encode(Module::getInstalledModule('WindowManager')->getWindowConfiguration('EditModelListing-'.$this->getModel())); ?>);
	window.setContent(htmlContent);
	window.setURL(this.url);
	window.display();
}); 
AjaxHTMLFetcher.setFetcher('new_ProductDetail',new URL(Ressource.getConfiguration().getValue('AliasName')+'model_editor/<?php echo $this->getConfParam('modelEditorProductDetail'); ?>/','model=ProductDetail&source=create'),function(htmlContent){

	var window = new Window();
	window.setConfiguration(<?php echo json_encode(Module::getInstalledModule('WindowManager')->getWindowConfiguration('EditModelListing-ProductDetail')); ?>);
	window.setContent(htmlContent);
	window.setURL(this.url);
	window.display();
}); 
</script>
<form class="well reload-on-model-editor-<?php echo $this->model; ?>-change reload-on-model-editor-ProductDetail-change">
<h1><?php echo Ressource::getCurrentLanguage()->getTranslation($this->getTitle()); ?></h1>
<table class="modelListing table table-striped">
	<thead>
		<tr>
			<?php foreach($this->columns as $column){ ?>
				<?php echo $column['head']->toHTML(); ?>
			<?php } ?>
		</tr>
	</thead>
	<tbody>
		<?php foreach($this->list as $line){ ?>
			<tr class="modelListingLine">
				<?php foreach($this->columns as $column){ ?>
					<?php echo $column['body']->toHTML($line); ?>
				<?php } ?>
			</tr>
		<?php } ?>
	</tbody>
	<tfoot>
		<tr class="change-page">
			<td colspan="<?php echo count($this->columns);?>">
				<table width="100%">
					<tr>
						<td align="left" width="50%">
								<a href="#"  class="AjaxHTMLFetcher btn btn-primary btn-mini" id="new_<?php echo $this->model; ?>"><?php echo Ressource::getCurrentLanguage()->getTranslation('New Category') ?></a>&nbsp;&nbsp;<a href="#"  class="AjaxHTMLFetcher btn btn-primary btn-mini" id="new_ProductDetail"><?php echo Ressource::getCurrentLanguage()->getTranslation('New Product') ?></a>
						</td>
						<td align="right" width="50%">
								<?php 
								if ($this->originalSize>$this->pageSize){
									for($x=0;$x<floor(($this->originalSize-1)/$this->pageSize)+1;$x++){ 
									?>
									<a href="#" class="btn <?php if ($x==$this->page){ echo "disabled"; }	?>" data-page="<?php echo $x; ?>"><?php echo $x+1; ?></a>
									<?php 
									}
								}
								?>
						</td>
					</tr>
				</table>
			</td>
		</tr>
	</tfoot>
</table>
</form>
