<?php 
ob_start();
include(Resource::getCurrentTemplate()->getURL("html/".$this->name.".phtml")); 
$bodyCore = ob_get_clean();

ob_start();
echo Hook::getHook($this->name.".head")->toHTML();
$headCore = ob_get_clean();

?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html>
	<head>
		<title><?php echo Resource::getCurrentPage()->getTitle() ?></title>
		<meta http-equiv="X-UA-Compatible" content="IE=8" />
		<?php $newCSSListe = $this->CSSFilterFlow->filterAndCompress($this->cssListe); ?>
		<?php 	foreach($newCSSListe as $arrayOfFiles){ ?>
		<?php 		foreach($arrayOfFiles as $file){  ?>
		<?php 			echo '<link rel="stylesheet" href="'.$file->toFullURL().'" type="text/css">'; ?>
		<?php 		} ?>
		<?php 	} ?>
		<?php 		$newJSListe = $this->JSFilterFlow->filterAndCompress($this->jsListe); ?>
		<?php 		foreach($newJSListe as $arrayOfFiles){ ?>
		<?php 			foreach($arrayOfFiles as $file){ ?>
		<?php 				echo '<script src="'.$file->toFullURL().'" language="javascript"></script>'; ?>
		<?php 			} ?>
		<?php 		} ?>
		<script>
			<?php $cssFiles = array(); ?>
			<?php $jsFiles = array(); ?>
			<?php $newCSSListe = $this->CSSFilterFlow->filter($this->cssListe); ?>
			<?php 	foreach($newCSSListe as $arrayOfFiles){ ?>
			<?php 		foreach($arrayOfFiles as $file){  ?>
			<?php 			$cssFiles[]=$file->toFullURL(); ?>
			<?php 		} ?>
			<?php 	} ?>
			<?php 		$newJSListe = $this->JSFilterFlow->filter($this->jsListe); ?>
			<?php 		foreach($newJSListe as $arrayOfFiles){ ?>
			<?php 			foreach($arrayOfFiles as $file){ ?>
			<?php 				$jsFiles[]=$file->toFullURL(); ?>
			<?php 			} ?>
			<?php 		} ?>
			var CSSLoadedFiles=<?php echo json_encode($cssFiles); ?>;
			var JSLoadedFiles=<?php echo json_encode($jsFiles); ?>;
		</script>
		<?php echo $headCore; ?>
	</head>
	<body>
		<?php echo $bodyCore ?>
	</body>
</html>
