<?php   Ressource::getCurrentPage()->addCSS(Ressource::getCurrentTemplate()->getFile(new File('css/module','MediaManager.css',false)),0); ?>
<?php   Ressource::getCurrentPage()->addJS(Ressource::getCurrentTemplate()->getFile(new File('js/module','MediaManager.js',false)),0); ?>
<?php Ressource::getCurrentLanguage()->init('module/ModelListingDescriptor.'.$this->getModel()); ?>

<?php Ressource::getCurrentLanguage()->init('module/ModelListingDescriptor'); ?>
<script> 
AjaxHTMLFetcher.setFetcher('new_<?php echo $this->model; ?>',new URL(Ressource.getConfiguration().getValue('AliasName')+'model_editor/<?php echo $this->getConfParam('modelEditor'); ?>/','model=<?php echo $this->model; ?>&source=create'),function(htmlContent){

	var window = new Window();
	window.setConfiguration(<?php echo json_encode(Module::getInstalledModule('WindowManager')->getWindowConfiguration('EditModelListing-'.$this->getModel())); ?>);
	window.setContent(htmlContent);
	window.setURL(this.url);
	window.display();
}); 
</script>
<div class="well reload-on-model-editor-<?php echo $this->model; ?>-change reload-on-model-editor-MediaFile-change context-menu-actionner files-uploader" data-context-menu="MediaManagerCreate">
<?php  if (Hook::hookExists("ModelEditor.form")) {?>
	<?php echo Hook::getHook("ModelEditor.form")->toHTML(); ?>
<?php }  ?>
<h1><?php echo Ressource::getCurrentLanguage()->getTranslation($this->getTitle()); ?></h1>
<div class="media-manager-listing">
		<?php foreach($this->list as $line){ ?>
			<tr>
				<?php foreach($this->columns as $column){ ?>
					<?php echo $column['body']->toHTML($line); ?>
				<?php } ?>
			</tr>
		<?php } ?>
		<br class="clearer">
</div>
</div>
<script>
	jQuery(document).ready(function(){
		jQuery('.file-uploader').each(function(){
			if (typeof(jQuery(this).data('object'))=='undefined'){
				var parent=jQuery(this);
				jQuery(this).data('object',parent);
				jQuery(this).html5Uploader({
					postUrl : 'MediaManager/upload/',
					onSuccess : function(event,file,html){
						parent.removeClass('loaded').removeClass('started').removeClass('error').addClass('loaded');
						var htmlElement = jQuery.parseJSON(html);
						FileUploader.propagateFileUploaded(parent,file,jQuery.parseJSON(htmlElement.html));
					},
					onServerLoadStart : function(){
						parent.removeClass('started').removeClass('error').addClass('started');
					},
					onServerError : function(){
						parent.removeClass('started').removeClass('error').addClass('error');
					}
				});
			}
		});
	});
</script>