<?php Resource::getCurrentLanguage()->init('module/ModelListing/EditCellML'); ?>
<?php if ($line->getParentModel()->getName()==$this->getListing()->getModel()){ 
	$modelEditor = $this->getConfParam('modelEditorCategory');
}else {
	$modelEditor = $this->getConfParam('modelEditorContent');
} ?>
<?php if (!isset($line->editable) || $line->editable){?>
<script> 
AjaxHTMLFetcher.setFetcher('edit_<?php print($this->getId($line)); ?>',new URL(Resource.getConfiguration().getValue('AliasName')+'model_editor/<?php echo $modelEditor; ?>/',<?php print(json_encode($this->getParams($line))); ?>),function(htmlContent){

	var window = new Window();
	window.setConfiguration(<?php echo json_encode(Module::getInstalledModule('WindowManager')->getWindowConfiguration('EditModelListing-'.$modelEditor)); ?>);
	window.setContent(htmlContent);
	window.setURL(this.url);
	window.display();
}); 
</script>
<td>
	<a href="#"  class="AjaxHTMLFetcher btn btn-primary btn-mini" id="edit_<?php print($this->getId($line)); ?>"><?php echo Resource::getCurrentLanguage()->getTranslation('Edit') ?></a>
</td>
<?php } else {?>
<td></td>
<?php }?>