<?php Ressource::getCurrentLanguage()->init('module/ModelListingDescriptor'); ?>
<?php Ressource::getCurrentLanguage()->init('module/ModelListingDescriptor.'.$this->getName()); ?>
<?php  Ressource::getCurrentPage()->addJS(Ressource::getCurrentTemplate()->getFile(new File('js/module','ModelListing.js',false)),0); ?>
<?php $modelEditorCategory =  $this->getConfParam('modelEditorCategory'); ?>
<?php $modelEditorContent =  $this->getConfParam('modelEditorContent'); ?>
<?php if (!empty($modelEditorCategory)){?>
<script> 
AjaxHTMLFetcher.setFetcher('new_<?php echo $this->model; ?>',new URL(Ressource.getConfiguration().getValue('AliasName')+'model_editor/<?php echo $this->getConfParam('modelEditorCategory'); ?>/',jQuery.extend({source:'create'},<?php echo json_encode($this->getCurrentCategoryParams()); ?>)),function(htmlContent){

	var window = new Window();
	window.setConfiguration(<?php echo json_encode(Module::getInstalledModule('WindowManager')->getWindowConfiguration('EditModelListing-'.$this->getModel())); ?>);
	window.setContent(htmlContent);
	window.setURL(this.url);
	window.display();
});
</script>
<?php }?>
<?php if (!empty($modelEditorContent)){?>
<script>
AjaxHTMLFetcher.setFetcher('new_<?php echo $this->contentRelation; ?>',new URL(Ressource.getConfiguration().getValue('AliasName')+'model_editor/<?php echo $this->getConfParam('modelEditorContent'); ?>/',jQuery.extend({source:'create'},<?php echo json_encode($this->getCurrentContentParams()); ?>)),function(htmlContent){

	var window = new Window();
	window.setConfiguration(<?php echo json_encode(Module::getInstalledModule('WindowManager')->getWindowConfiguration('EditModelListing-'.$this->getModel())); ?>);
	window.setContent(htmlContent);
	window.setURL(this.url);
	window.display();
}); 
</script>
<?php }?>
<div class="well reload-on-model-editor-<?php echo $this->model; ?>-change reload-on-model-editor-<?php echo $this->getConfParam('modelContent'); ?>-change">
<legend><?php echo Ressource::getCurrentLanguage()->getTranslation($this->getTitle()); ?></legend>
<table class="modelListing table table-striped">
	<?php if ($this->originalSize>0){?>
		<thead>
			<tr>
				<?php foreach($this->columns as $column){ ?>
					<?php echo $column['head']->toHTML(); ?>
				<?php } ?>
			</tr>
		</thead>
	<?php }?>
	<tbody>
		<?php foreach($this->list as $line){ ?>
			<tr>
				<?php foreach($this->columns as $column){ ?>
					<?php echo $column['body']->toHTML($line); ?>
				<?php } ?>
			</tr>
		<?php } ?>
	</tbody>
	<tfoot>
		<tr class="change-page">
			<?php
				$first = true; 
				$count = 0;
				foreach($this->columns as $column){ 
					$count++;
					if ($first){
					?>
					<td align="left">
						<?php if (!empty($modelEditorCategory)){?>
							<a href="#"  class="AjaxHTMLFetcher btn btn-primary btn-mini" id="new_<?php echo $this->model; ?>"><?php echo Ressource::getCurrentLanguage()->getTranslation('New '.$this->model) ?></a>&nbsp;&nbsp;
						<?php }?>
						<?php if (!empty($modelEditorContent)){?>
							<a href="#"  class="AjaxHTMLFetcher btn btn-primary btn-mini" id="new_<?php echo $this->contentRelation; ?>"><?php echo Ressource::getCurrentLanguage()->getTranslation('New '.$this->contentRelation) ?></a>
						<?php }?>
					</td>
					<?php }
					elseif ($count<count($this->columns)) { ?>
					<td align="right"></td>
				<?php }else{ ?>
					<td align="right">
							<?php 
							if ($this->originalSize>0&&$this->pageSize>0&&$this->originalSize>$this->pageSize){
								for($x=0;$x<floor(($this->originalSize-1)/$this->pageSize)+1;$x++){ 
								?>
								<a href="#" class="btn <?php if ($x==$this->page){ echo "disabled"; }	?>" data-page="<?php echo $x; ?>"><?php echo $x+1; ?></a>
								<?php 
								}
							}
							?>
					</td>
				<?php }
					$first = false;
				} ?>
		</tr>
	</tfoot>
</table>
</div>
