<?php Resource::getCurrentLanguage()->init('module/ModelListing/DeleteCellML'); ?>
<script> 
var fetcher = AjaxHTMLFetcher.setFetcher('delete_<?php print($this->getId($line)); ?>',new URL(Resource.getConfiguration().getValue('AliasName')+'model_editor/<?php echo $this->getConfParam('modelEditor'); ?>/delete/',<?php print(json_encode($this->getParams($line))); ?>),function(htmlContent){
	ReloadManager.propagateChangeEvent(jQuery('#delete_<?php print($this->getId($line)); ?>'));
});
fetcher.beforeCall=function(){
	this.continueCall=confirm('Êtes vous sûr de vouloir supprimer cet élement ?');
};
</script>
<td>
	<a href="#"  class="AjaxHTMLFetcher btn btn-inverse reload-change-propagator btn-mini" data-reload-change-types="<?php echo implode($this->getChangeTypes()," "); ?>" id="delete_<?php print($this->getId($line)); ?>"><?php echo Resource::getCurrentLanguage()->getTranslation('Delete') ?></a>
</td>
