<?php Ressource::getCurrentLanguage()->init('module/DeleteCellML'); ?>
<script> 
AjaxHTMLFetcher.setFetcher('delete_<?php print($this->getId($line)); ?>',new URL('/'+Ressource.getConfiguration().getValue('AliasName')+'model_editor/<?php echo $this->getConfParam('modelEditor'); ?>/delete/','<?php print($this->getParams($line)); ?>'),function(htmlContent){
	ReloadManager.propagateChangeEvent(jQuery('#delete_<?php print($this->getId($line)); ?>'));
}); 
</script>
<td>
	<a href="#"  class="AjaxHTMLFetcher btn btn-inverse reload-change-propagator" data-reload-change-type="model-editor-<?php echo $this->getListing()->getModel(); ?>" id="delete_<?php print($this->getId($line)); ?>"><?php echo Ressource::getCurrentLanguage()->getTranslation('Delete') ?></a>
</td>
