<?php Ressource::getCurrentLanguage()->init('module/EditCellML'); ?>
<script> 
AjaxHTMLFetcher.setFetcher('edit_<?php print($this->getId($line)); ?>',new URL(Ressource.getConfiguration().getValue('AliasName')+'model_editor/<?php echo $this->getConfParam('modelEditor'); ?>/',<?php print(json_encode($this->getParams($line))); ?>),function(htmlContent){

	var window = new Window();
	window.setConfiguration(<?php echo json_encode(Module::getInstalledModule('WindowManager')->getWindowConfiguration('EditModelListing-'.$this->getListing()->getModel())); ?>);
	window.setContent(htmlContent);
	window.setURL(this.url);
	window.display();
}); 
</script>
<td>
	<a href="#"  class="AjaxHTMLFetcher btn btn-primary btn-mini" id="edit_<?php print($this->getId($line)); ?>"><?php echo Ressource::getCurrentLanguage()->getTranslation($this->getConfParam('title')!=""?$this->getConfParam('title'):'Edit'); ?></a>
</td>
