<script>
AjaxHTMLFetcher.setFetcher('icon_model_hook_<?php echo $this->getConfParam('hook'); ?>',new URL(Resource.getConfiguration().getValue('AliasName')+'admin/hook/<?php echo $this->getConfParam('hook'); ?>/',new Object()),function(htmlContent){
	var window = new Window();
	window.setConfiguration(<?php echo json_encode(Module::getInstalledModule('WindowManager')->getWindowConfiguration('Hook-'.$this->getConfParam('hook'))); ?>);
	window.setContent(htmlContent);
	window.setURL(new URL(Resource.getConfiguration().getValue('AliasName')+'admin/hook/<?php echo $this->getConfParam('hook'); ?>/',new Object()));
	window.display();
}); </script>
<div class="icon">
	<a href="#" class="AjaxHTMLFetcher" id="icon_model_hook_<?php echo $this->getConfParam('hook'); ?>">
			<i class="icon-white icon-<?php echo $this->getConfParam('icon'); ?>"></i><?php echo Resource::getCurrentLanguage()->getTranslation($this->text); ?>
	</a>
</div>
