<script>
AjaxHTMLFetcher.setFetcher('icon_test',new URL(Resource.getConfiguration().getValue('AliasName')+'model_listing/test/',new Object()),function(htmlContent){
	var window = new Window();
	window.setConfiguration(<?php echo json_encode(Module::getInstalledModule('WindowManager')->getWindowConfiguration('icon_test')); ?>);
	window.setContent(htmlContent);
	window.setURL(this.url);
	window.display();
}); </script>
<div class="icon">
	<a href="#" class="AjaxHTMLFetcher" id="icon_test">
		<i class="icon-white icon-<?php echo $this->getConfParam('icon'); ?>"></i><?php echo Resource::getCurrentLanguage()->getTranslation($this->text); ?>
	</a>
</div>
