<script>
AjaxHTMLFetcher.setFetcher('icon_model_listing_<?php echo $this->getConfParam('modelListing'); ?>',new URL(Resource.getConfiguration().getValue('AliasName')+'model_listing/<?php echo $this->getConfParam('modelListing'); ?>/',new Object()),function(htmlContent){
	var window = new Window();
	window.setConfiguration(<?php echo json_encode(Module::getInstalledModule('WindowManager')->getWindowConfiguration('icon_test')); ?>);
	window.setContent(htmlContent);
	window.setURL(new URL(Resource.getConfiguration().getValue('AliasName')+'model_listing/<?php echo $this->getConfParam('modelListing'); ?>/',new Object()));
	window.display();
}); </script>
<div class="icon">
	<a href="#" class="AjaxHTMLFetcher" id="icon_model_listing_<?php echo $this->getConfParam('modelListing'); ?>">
		<i class="icon-white icon-<?php echo $this->getConfParam('icon'); ?>"></i><?php echo Resource::getCurrentLanguage()->getTranslation($this->text); ?>
	</a>
</div>
