<script>
AjaxHTMLFetcher.setFetcher('icon_test',new URL('/'+Ressource.getConfiguration().getValue('AliasName')+'model_listing/test/',''),function(htmlContent){
	var window = new Window();
	window.setConfiguration(<?php echo json_encode(Module::getInstalledModule('WindowManager')->getWindowConfiguration('icon_test')); ?>);
	window.setContent(htmlContent);
	window.setURL(this.url);
	window.display();
}); </script>
<div class="icon">
	<a href="#" class="AjaxHTMLFetcher" id="icon_test">
		<div class="image">
			<img src="<?php echo Ressource::getCurrentTemplate()->getFile(File::createFromURL($this->image),true)->toFullURL(); ?>">
		</div>
		<div class="title">
			<?php echo$this->text ?>
		</div>
	</a>
</div>

	