<script>
AjaxHTMLFetcher.setFetcher('icon_page_<?php echo md5($this->getConfParam('page')); ?>',new URL(Resource.getConfiguration().getValue('AliasName')+'<?php echo $this->getConfParam('page'); ?>',new Object()),function(htmlContent){
	var window = new Window();
	window.setConfiguration(<?php echo json_encode(Module::getInstalledModule('WindowManager')->getWindowConfiguration('page')); ?>);
	window.setContent(htmlContent);
	window.setURL(new URL(Resource.getConfiguration().getValue('AliasName')+'<?php echo $this->getConfParam('page'); ?>',new Object()));
	window.display();
}); </script>
<div class="icon">
	<a href="#" class="AjaxHTMLFetcher" id="icon_page_<?php echo md5($this->getConfParam('page')); ?>">
		<i class="icon-white icon-<?php echo $this->getConfParam('icon'); ?>"></i><?php echo Resource::getCurrentLanguage()->getTranslation($this->text); ?>
	</a>
</div>
