<script>
AjaxHTMLFetcher.setFetcher('icon_model_listing_<?php echo $this->getConfParam('modelListing'); ?>',new URL('/'+Ressource.getConfiguration().getValue('AliasName')+'model_listing/<?php echo $this->getConfParam('modelListing'); ?>/',''),function(htmlContent){
	var window = new Window();
	window.setConfiguration(<?php echo json_encode(Module::getInstalledModule('WindowManager')->getWindowConfiguration('icon_test')); ?>);
	window.setContent(htmlContent);
	window.setURL(new URL('/'+Ressource.getConfiguration().getValue('AliasName')+'model_listing/<?php echo $this->getConfParam('modelListing'); ?>/',''));
	window.display();
}); </script>
<div class="icon btn">
	<a href="#" class="AjaxHTMLFetcher" id="icon_model_listing_<?php echo $this->getConfParam('modelListing'); ?>">
		<div class="image">
			<img src="<?php echo Ressource::getCurrentTemplate()->getFile(File::createFromURL($this->image),true)->toFullURL(); ?>">
		</div>
		<div class="title">
			<?php echo Ressource::getCurrentLanguage()->getTranslation($this->text); ?>
		</div>
	</a>
</div>

