<?php Ressource::getCurrentLanguage()->init('module/AjaxConnectionManager'); ?>
<?php  $this->addJS(Ressource::getCurrentTemplate()->getFile(new File('js/module','AjaxConnectionManager.js',false)),0); ?>
<legend><?php echo Ressource::getCurrentLanguage()->getTranslation("Your session has expired, please login again"); ?></legend>
<br>
<br>
<form action="" style="margin : 0px;" method="post" id="ajaxConnection">
	<center>
		<div class="connectionTitreDiv"> <?php echo Ressource::getCurrentLanguage()->getTranslation("username") ?> : </div><div class="connectionInputDiv"><input type="text" name="userInput" class="connectionInput"></div>
		<div class="connectionTitreDiv"> <?php echo Ressource::getCurrentLanguage()->getTranslation("password") ?>: </div><div class="connectionInputDiv"><input type="password" name="passwordInput" class="connectionInput"></div>
		<br>
		<div class="connectionTopDiv"><input type="submit" value="<?php echo Ressource::getCurrentLanguage()->getTranslation("Login") ?>" class="btn btn-primary connectionInput" id="connectionSubmit"></div><br class="clearer"/>
	</center>
</form>
<?php if (Ressource::getUserSpace()->getSlot('ADMIN')->hasRight('ACCESS_ADMIN')) {?>
<script>
jQuery('#ajaxConnection').closest('.reload-change-listener').data('object').close();
</script>
<?php } ?>