<?php  $this->addJS(Ressource::getCurrentTemplate()->getFile(new File('js/module','ContextMenu.js',false)),2); ?>
<?php  $this->addCSS(Ressource::getCurrentTemplate()->getFile(new File('css/module','ContextMenu.css',false)),2); ?>
<script>
<?php foreach($this->htmlProducer->getConfParam('descriptors') as $descriptor){ ?>
	ContextMenu.addContextMenu(ContextMenu.readFromJSON(<?php echo json_encode($this->getElementDescriptor($descriptor)); ?>));
<?php }?>
</script>