<?php  $this->addJS(Resource::getCurrentTemplate()->getFile(new File('js/module','DesktopManager.js',false)),2); ?>
<?php  $this->addJS(Resource::getCurrentTemplate()->getFile(new File('js','jquery.js',false)),0); ?>
<?php  $this->addCSS(Resource::getCurrentTemplate()->getFile(new File('css/module','DesktopManager.css',false)),0); ?>
<?php  Resource::getCurrentLanguage()->init('module/DesktopManager'); ?>
<div class="desktop">
		<h1><?php echo Resource::getCurrentLanguage()->getTranslation("Administration"); ?></h1>
<?php foreach($this->icons as $icon){ ?>
	<?php echo $icon->toHTML(); ?>
<?php } ?>
</div>
