<?php $loadedTranslations = Ressource::getCurrentLanguage()->init('module/JSRessource');?>
<?php  $this->addJS(Ressource::getCurrentTemplate()->getFile(new File('js/module','JSRessource.js',false)),2); ?>
<script>
var Ressource=new Ressource();
Ressource.setConfiguration(new Configuration());
Ressource.getConfiguration().setValue('AliasName','<?php echo Ressource::getConfiguration()->getValue('AliasName'); ?>');
Ressource.getConfiguration().setValue('TemplateDirectory','<?php echo Ressource::getCurrentTemplate()->getFile(new File('','',true))->toFullURL(); ?>');
Ressource.getConfiguration().setValue('domainName','<?php echo Ressource::getConfiguration()->getValue('domainName'); ?>');


Ressource.setLanguage(new Language(<?php echo Ressource::getCurrentLanguage()->getId() ?>,'<?php echo Ressource::getCurrentLanguage()->getName() ?>'));
<?php foreach($loadedTranslations as $key=>$loadedTranslation){ ?>
	Ressource.getLanguage().setTranslation('<?php echo $key?>',<?php echo $loadedTranslation; ?>);
<?php } ?>
</script>