<?php  Ressource::getCurrentPage()->addJS(Ressource::getCurrentTemplate()->getFile(new File('js','jquery.js',false)),0); ?>
<?php  Ressource::getCurrentPage()->addCSS(Ressource::getCurrentTemplate()->getFile(new File('css/module','LanguageChooser.css',false)),0); ?>
<?php  Ressource::getCurrentPage()->addJS(Ressource::getCurrentTemplate()->getFile(new File('js/module','LanguageChooser.js',false)),2); ?>
<div class="LanguageFieldME-languageChooser-container">
	<?php $languages=Language::getAvailableLanguages() ; ?>
	<?php foreach($languages as $language){ ?>
		<a href="<?php echo $language->getId(); ?>" class="LanguageFieldME-languageChooser <?php echo (Ressource::getCurrentLanguage()->getId()==$language->getId()?"LanguageFieldME-default":"") ?>"><img src="<?php echo Ressource::getCurrentTemplate()->getFile(new File("media/image/share",String::strtolower($language->getName()).".jpg",0))->toFullURL(); ?>"></a>
	<?php } ?>
</div>
<script>
jQuery(document).ready(function(){
	jQuery('.LanguageFieldME-default').click();
	jQuery('.LanguageFieldME-default').removeClass('LanguageFieldME-default');
});
</script>
