<?php  $this->addJS(Ressource::getCurrentTemplate()->getFile(new File('js','jquery.js',false)),0); ?>
<?php  $this->addJS(Ressource::getCurrentTemplate()->getFile(new File('lib/jQueryUI','jquery-ui-1.8.19.custom.min.js',false)),1); ?>
<?php  $this->addJS(Ressource::getCurrentTemplate()->getFile(new File('lib/jQueryWindow','jquery.window.min.js',false)),2); ?>
<?php  $this->addJS(Ressource::getCurrentTemplate()->getFile(new File('js/module','WindowManager.js',false)),3); ?>
<?php  $this->addCSS(Ressource::getCurrentTemplate()->getFile(new File('lib/jQueryWindow/css','jquery.window.css',false)),0); ?>
<?php  $this->addCSS(Ressource::getCurrentTemplate()->getFile(new File('lib/jQueryUI/css','jquery-ui-1.8.16.custom.css',false)),0); ?>
