<?php 
ob_start();
include(Ressource::getCurrentTemplate()->getURL("html/mail/".$this->name.".phtml")); 
$bodyCore = ob_get_clean();

ob_start();
echo Hook::getHook($this->name.".head")->toHTML();
$headCore = ob_get_clean();

?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html>
	<head>
		<title><?php echo Ressource::getCurrentPage()->getTitle() ?></title>
		<?php echo $headCore; ?>
	</head>
	<body>
		<?php echo $bodyCore ?>
	</body>
</html>
