
<tr>
<td colspan="2" class="control-group" width="75%">
	<label class="checkbox">
		<input type="checkbox" name="<?php echo $this->getName(); ?>" class="" <?php echo $this->getValue($element)?"checked":""; ?> data-field-name="<?php echo htmlentities(Ressource::getCurrentLanguage()->getTranslation($this->title)); ?>">
		<?php echo Ressource::getCurrentLanguage()->getTranslation($this->title); ?>
	</label>
</td>	
</tr>
