<?php  Ressource::getCurrentPage()->addJS(Ressource::getCurrentTemplate()->getFile(new File('js','jquery.js',false)),0); ?>
<?php  Ressource::getCurrentPage()->addJS(Ressource::getCurrentTemplate()->getFile(new File('lib/jquery-miniColors','jquery.miniColors.min.js',false)),1); ?>
<?php  Ressource::getCurrentPage()->addCSS(Ressource::getCurrentTemplate()->getFile(new File('lib/jquery-miniColors','jquery.miniColors.css',false)),2); ?>
<tr>
<td>
	<?php echo Ressource::getCurrentLanguage()->getTranslation($this->title); ?>
</td>
<td class="control-group" width="75%">
	<input size="7" type="hidden" name="<?php echo $this->getName(); ?>" class="span3 color-picker" value="<?php echo $this->getValue($element); ?>" data-field-name="<?php echo htmlentities(Ressource::getCurrentLanguage()->getTranslation($this->title)); ?>">
	<script>
		jQuery(document).ready(function(){
			jQuery('.color-picker').miniColors({
				letterCase: 'uppercase'
			});
		});
	</script>
</td>	
</tr>
