<?php  Resource::getCurrentPage()->addJS(Resource::getCurrentTemplate()->getFile(new File('js','jquery.js',false)),0); ?>
<?php  Resource::getCurrentPage()->addJS(Resource::getCurrentTemplate()->getFile(new File('lib/jQueryUI','jquery-ui-1.8.19.custom.min.js',false)),1); ?>
<?php  Resource::getCurrentPage()->addJS(Resource::getCurrentTemplate()->getFile(new File('js/module','Datetime.js',false)),3); ?>
<?php  Resource::getCurrentPage()->addCSS(Resource::getCurrentTemplate()->getFile(new File('css/module','Datetime.css',false)),2); ?>
<tr>
<td>
	<?php echo Resource::getCurrentLanguage()->getTranslation($this->title); ?>
</td>
<?php $date = $this->getValue($element) instanceof Date?$this->getValue($element):Date::getNow();  ?>
<td class="control-group" width="75%">
	<input type="text" name="<?php echo $this->getName(); ?>" class="span3 datetime" value="<?php echo $date->format('d/m/Y H:i:s'); ?>" data-field-name="<?php echo htmlentities(Resource::getCurrentLanguage()->getTranslation($this->title)); ?>">
	<script>
	jQuery(document).ready(function(){
		jQuery('.datetime').each(function(){
			if (typeof jQuery(this).data('object') == "undefined"){
				jQuery(this).datetimepicker();
			}
		});
	});
	</script>
</td>	
</tr>
