<?php Ressource::getCurrentLanguage()->init('module/ModelEditorDescriptor.'.$this->getName()); ?>
<?php  Ressource::getCurrentPage()->addCSS(Ressource::getCurrentTemplate()->getFile(new File('css/module','ModelEditor.css',false)),0); ?>
<form class="well reload-change-propagator model-editor-form field-validator-target" data-field-validator="<?php echo $this->getName() ?>" data-reload-change-types="<?php echo implode($this->getChangeTypes()," "); ?>">
<?php  if (Hook::hookExists("ModelEditor.form")) {?>
	<?php echo Hook::getHook("ModelEditor.form")->toHTML(); ?>
<?php }  ?>
<table id="<?php echo $this->getSerializedId(); ?>" class="modelEditor table table-striped">
	<thead>
		<tr>
			<?php echo $this->getTitle()->toHTML($this->fetchedData); ?>
		</tr>
	</thead>
	<tbody>
		<?php foreach($this->inputs as $input){ ?>
			<?php echo $input->toHTML($this->fetchedData); ?>
		<?php } ?>
	</tbody>
</table>
</form>
