<tr class="reload-on-model-editor-<?php echo $this->getConfParam('listReference'); ?>-change">
<td colspan="2">
<div>
<?php if ($this->getConfParam('modelListing')!=''){?>
<script>
	AjaxHTMLFetcher.setFetcher('list_model_<?php echo $this->getName(); ?>',new URL(Ressource.getConfiguration().getValue('AliasName')+'model_listing/<?php echo $this->getConfParam('modelListing'); ?>/',new Object()),function(htmlContent){
		var window = new Window();
		window.setConfiguration(<?php echo json_encode(Module::getInstalledModule('WindowManager')->getWindowConfiguration('icon_test')); ?>);
		window.setContent(htmlContent);
		window.setURL(new URL(Ressource.getConfiguration().getValue('AliasName')+'model_listing/<?php echo $this->getConfParam('modelListing'); ?>/',new Object()));
		window.display();
	}); 
</script>
<a id="list_model_<?php echo $this->getName(); ?>" class="AjaxHTMLFetcher btn btn-primary btn-list-modellist" href="#"><?php echo Ressource::getCurrentLanguage()->getTranslation('Edit the list'); ?></a>
<?php } ?>
</div>
<?php echo $this->getInnerModelEditor()->toHTML() ?>
</td>	
</tr>

