<?php Ressource::getCurrentLanguage()->init('module/ModelEditorDescriptor.'.$this->getModel()); ?>
<form class="well reload-change-propagator model-editor-form field-validator-target" data-field-validator="<?php echo $this->getName() ?>" data-reload-change-type="model-editor-<?php echo $this->model; ?>">
<?php  if (Hook::hookExists("ModelEditor.form")) {?>
	<?php echo Hook::getHook("ModelEditor.form")->toHTML(); ?>
<?php }  ?>
<table id="<?php echo $this->getSerializedId(); ?>" class="modelEditor table table-striped">
	<thead>
		<tr>
			<?php echo $this->getTitle()->toHTML($this->fetchedData); ?>
		</tr>
	</thead>
	<tbody>
		<?php foreach($this->inputs as $input){ ?>
			<?php echo $input->toHTML($this->fetchedData); ?>
		<?php } ?>
	</tbody>
	<tfoot>
		<tr>
			<td colspan="2" align="center">
				<input type="button" class="model-editor-cancel-button btn" value="<?php echo Ressource::getCurrentLanguage()->getTranslation('Cancel'); ?>">
				<input type="submit" class="model-editor-save-button btn btn-primary" value="<?php echo Ressource::getCurrentLanguage()->getTranslation('Save'); ?>">
				<?php if ($this->getSource()!=ModelData::$SOURCE_NEW) {?>
					<input type="button" class="model-editor-delete-button btn btn-warning" value="<?php echo Ressource::getCurrentLanguage()->getTranslation('Delete'); ?>">
				<?php }?>
			</td>
		</tr>
	</tfoot>
</table>
</form>
