<tr class="reload-on-model-editor-<?php echo $this->getConfParam('listReference'); ?>-change">
<td>


	<?php echo Resource::getCurrentLanguage()->getTranslation($this->title); ?>
</td>
<td> 
<div>

<select name="<?php echo $this->getName(); ?>">
<?php 
foreach($element['reference'] as $elt){
    $selected=false;
    if ($this->getValue($elt)==$this->getValue($element['simple'])){
        $selected=true;
    }
    
    ?>
    	<option  value="<?php echo $this->getValue($elt); ?>" <?php echo $selected?" selected ":""; ?>><?php echo $this->getNameValue($elt); ?></option>
    <?php 
}
?>
</select>
<?php if ($this->getConfParam('modelListing')!=''){?>
<script>
	AjaxHTMLFetcher.setFetcher('list_model_<?php echo $this->getName(); ?>',new URL(Resource.getConfiguration().getValue('AliasName')+'model_listing/<?php echo $this->getConfParam('modelListing'); ?>/',new Object()),function(htmlContent){
		var window = new Window();
		window.setConfiguration(<?php echo json_encode(Module::getInstalledModule('WindowManager')->getWindowConfiguration('icon_test')); ?>);
		window.setContent(htmlContent);
		window.setURL(new URL(Resource.getConfiguration().getValue('AliasName')+'model_listing/<?php echo $this->getConfParam('modelListing'); ?>/',new Object()));
		window.display();
	}); 
</script>
<a id="list_model_<?php echo $this->getName(); ?>" class="AjaxHTMLFetcher btn btn-primary btn-list-modellist" href="#"><?php echo Resource::getCurrentLanguage()->getTranslation('Edit the list'); ?></a>
<?php } ?>
</div>
</td>	
</tr>

