<tr>
<td>
	<?php echo Ressource::getCurrentLanguage()->getTranslation($this->title); ?>
</td>
<td class="control-group" width="75%">
	<input type="text" name="<?php echo $this->getName(); ?>" class="span3" value="<?php echo htmlentities($this->getValue($element),ENT_COMPAT,"UTF-8"); ?>" data-field-name="<?php echo htmlentities(Ressource::getCurrentLanguage()->getTranslation($this->title)); ?>">
</td>	
</tr>

