<?php Ressource::getCurrentLanguage()->init('module/ModelEditorDescriptor.'.$this->getName()); ?>
<?php  Ressource::getCurrentPage()->addCSS(Ressource::getCurrentTemplate()->getFile(new File('css/module','ModelEditor.css',false)),0); ?>
<?php  Ressource::getCurrentPage()->addCSS(Ressource::getCurrentTemplate()->getFile(new File('css/module/ModelEditor','TabModelEditor.css',false)),0); ?>
<?php  Ressource::getCurrentPage()->addJS(Ressource::getCurrentTemplate()->getFile(new File('js','jquery.js',false)),0); ?>
<?php  Ressource::getCurrentPage()->addJS(Ressource::getCurrentTemplate()->getFile(new File('js/module/ModelEditor','TabModelEditor.js',false)),1); ?>
<form class="well reload-change-propagator model-editor-form field-validator-target" data-field-validator="<?php echo $this->getName() ?>" data-reload-change-type="model-editor-<?php echo $this->model; ?>">
<?php  if (Hook::hookExists("ModelEditor.form")) {?>
	<?php echo Hook::getHook("ModelEditor.form")->toHTML(); ?>
<?php }  ?>
<div class="tabs">
	<ul class="tabTitleGroup nav nav-pills navbar-inner">
		<?php $count=0; ?>
		<?php foreach($this->tabs as $tab){ ?>
			<li data-tab="<?php echo $count ;?>" class="tabTitle tabTitle<?php echo $count ;?> <?php echo ($count==0?"currentTabTitle active":""); $count++; ?>">
				<a href="#"><?php echo Ressource::getCurrentLanguage()->getTranslation($tab->getTitle()); ?></a>
			</li>
		<?php } ?>
		<br class="clearer">
	</ul>
	<div class="tabViewPort">
		<div class="tabGroup">
			<?php $count=0; ?>
			<?php foreach($this->tabs as $tab){ ?>
				<div class="tab tab<?php echo $count ;?> <?php echo ($count==0?"currentTab":""); ?>">
					<table id="<?php echo $this->getSerializedId(); ?>" class="modelEditor table table-striped">
						<?php if ($count==0) { ?>
							<thead>
								<tr>
									<?php echo $this->getTitle()->toHTML($this->fetchedData); ?>
								</tr>
							</thead>
						<?php } ?>
						<tbody>
							<?php foreach($tab->getInputs() as $input){ ?>
								<?php echo $input->toHTML($this->fetchedData); ?>
							<?php } ?>
						</tbody>
						<tfoot>
							<tr>
								<td colspan="2" align="center">
									<?php if ($tab->displayButtons()){?>
										<input type="button" class="model-editor-cancel-button btn" value="<?php echo Ressource::getCurrentLanguage()->getTranslation('Cancel'); ?>">
										<input type="submit" class="model-editor-save-button btn btn-primary" value="<?php echo Ressource::getCurrentLanguage()->getTranslation('Save'); ?>">
										<?php if ($this->getSource()!=ModelData::$SOURCE_NEW) {?>
											<input type="button" class="model-editor-delete-button btn btn-warning" value="<?php echo Ressource::getCurrentLanguage()->getTranslation('Delete'); ?>">
										<?php }?>
									<?php }?>
								</td>
							</tr>
						</tfoot>
					</table>
				</div>
				<?php $count++; ?>
			<?php } ?>
		</div>
	</div>
</div>
</form>
