<?php  Resource::getCurrentPage()->addCSS(Resource::getCurrentTemplate()->getFile(new File('css/module/ModelEditor','LanguageFieldME.css',false)),0); ?>
<?php  Resource::getCurrentPage()->addCSS(Resource::getCurrentTemplate()->getFile(new File('css/module/ModelEditor','TextareaLanguageFieldME.css',false)),0); ?>
<tr>
<td colspan="2">
	<?php echo Resource::getCurrentLanguage()->getTranslation($this->title); ?>
</td>
</tr>
<tr>
<td height="300" colspan="2">
	<div  class="LanguageFieldME-container control-group">
		<?php $languages=Language::getAvailableLanguages() ; ?>
		<?php foreach($languages as $language){ ?>
			<div class="LanguageFieldME-wrapper  LanguageFieldME-lng<?php echo $language->getId(); ?> <?php echo $this->getConfParam('class') ?> <?php if ($language->getId()==Resource::getCurrentLanguage()->getId()) { echo "LanguageFieldME-default"; }?>" data-idLang="<?php echo $language->getId(); ?>">
				<textarea class="LanguageFieldME TextareaLanguageFieldME" name="<?php echo $this->getName(); ?>[<?php echo $language->getId() ?>]" data-field-name="<?php echo htmlentities(Resource::getCurrentLanguage()->getTranslation($this->title)); ?>"><?php echo htmlentities($this->getValueLang($element,$language->getId()),ENT_COMPAT,"UTF-8"); ?></textarea>
			</div>
		<?php } ?>
	</div>
</td>	
</tr>

