<?php  Ressource::getCurrentPage()->addCSS(Ressource::getCurrentTemplate()->getFile(new File('css/module/ModelEditor','LanguageFieldME.css',false)),0); ?>
<?php  Ressource::getCurrentPage()->addCSS(Ressource::getCurrentTemplate()->getFile(new File('css/module/ModelEditor','TextareaLanguageFieldME.css',false)),0); ?>
<tr>
<td colspan="2">
	<?php echo Ressource::getCurrentLanguage()->getTranslation($this->title); ?>
</td>
</tr>
<tr>
<td  class="LanguageFieldME-container" height="300" colspan="2">
	<div  class="LanguageFieldME-container control-group">
		<?php $languages=Language::getAvailableLanguages() ; ?>
		<?php foreach($languages as $language){ ?>
			<textarea class="LanguageFieldME TextareaLanguageFieldME LanguageFieldME-lng<?php echo $language->getId(); ?> <?php echo $this->getConfParam('class') ?>" name="<?php echo $this->getName(); ?>[<?php echo $language->getId() ?>]" data-field-name="<?php echo htmlentities(Ressource::getCurrentLanguage()->getTranslation($this->title)); ?>"><?php echo htmlentities($this->getValueLang($element,$language->getId()),ENT_COMPAT,"UTF-8"); ?></textarea>
		<?php } ?>
	</div>
</td>	
</tr>

