<?php  Resource::getCurrentPage()->addCSS(Resource::getCurrentTemplate()->getFile(new File('css/module/ModelEditor','TextareaFieldME.css',false)),0); ?>
<tr>
	<td colspan="2">
		<?php echo Resource::getCurrentLanguage()->getTranslation($this->title); ?>
	</td>
</tr>
<tr>
	<td class="control-group" width="75%" colspan="2">
		<textarea name="<?php echo $this->getName(); ?>" class="TextareaFieldME" data-field-name="<?php echo htmlentities(Resource::getCurrentLanguage()->getTranslation($this->title)); ?>"><?php echo htmlentities($this->getValue($element),ENT_COMPAT,"UTF-8"); ?></textarea>
	</td>	
</tr>
